# Generated by Django 3.2.5 on 2021-07-15 04:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0002_auto_20210714_1711'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='thumbnail_url',
            field=models.URLField(null=True),
        ),
    ]
